# -*- coding: utf-8 -*-
"""Reglas para procedimientos almacenados normales."""

from app.reglas.reglas_base import ReglaDiccionario

REGLAS_PROCEDIMIENTOS_NORMALES = {
    "PROCEDIMIENTO_SIN_ESQUEMA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_SIN_ESQUEMA",
        nombre="Procedimiento sin esquema",
        severidad="alto",
        descripcion="El procedimiento debe indicar su esquema (CREATE y ALTER).",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_SIN_PREFIJO_PA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_SIN_PREFIJO_PA",
        nombre="Nombre sin prefijo PA_",
        severidad="alto",
        descripcion="Al crearlo, el nombre sigue el formato Esquema.PA_Tabla_Acción_Finalidad.",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_NOMBRE_INCOMPLETO": ReglaDiccionario(
        codigo="PROCEDIMIENTO_NOMBRE_INCOMPLETO",
        nombre="Nombre de procedimiento incompleto",
        severidad="alto",
        descripcion="Al crearlo, el nombre indica la tabla y la acción: PA_Tabla_Acción_Finalidad.",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_ACCION_NO_ABREVIADA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_ACCION_NO_ABREVIADA",
        nombre="Acción sin abreviar",
        severidad="alto",
        descripcion="Las acciones estándar se abrevian: Sel (consultar), Upd (actualizar), Ins (insertar) y Del (eliminar).",
        alcance="procedimiento",
        activo=True,
    ),
    "WHILE_PROHIBIDO": ReglaDiccionario(
        codigo="WHILE_PROHIBIDO",
        nombre="WHILE prohibido",
        severidad="alto",
        descripcion="No se permite el uso de bucles WHILE en procedimientos normales; use operaciones basadas en conjuntos.",
        alcance="procedimiento",
        activo=True,
    ),
    "GOTO_PROHIBIDO": ReglaDiccionario(
        codigo="GOTO_PROHIBIDO",
        nombre="GOTO prohibido",
        severidad="alto",
        descripcion="No se permite el uso de GOTO en procedimientos normales.",
        alcance="procedimiento",
        activo=True,
    ),
    "MERGE_PROHIBIDO": ReglaDiccionario(
        codigo="MERGE_PROHIBIDO",
        nombre="MERGE prohibido",
        severidad="alto",
        descripcion="No se permite la sentencia MERGE en procedimientos normales.",
        alcance="procedimiento",
        activo=True,
    ),
    "COLLATE_EN_PREDICADO": ReglaDiccionario(
        codigo="COLLATE_EN_PREDICADO",
        nombre="COLLATE en predicado",
        severidad="alto",
        descripcion="No debe usarse COLLATE dentro de condiciones WHERE o JOIN; debe definirse en la tabla temporal o columna.",
        alcance="procedimiento",
        activo=True,
    ),
    "STUFF_FOR_XML_PATH_PROHIBIDO": ReglaDiccionario(
        codigo="STUFF_FOR_XML_PATH_PROHIBIDO",
        nombre="STUFF con FOR XML PATH prohibido",
        severidad="alto",
        descripcion="Se debe reemplazar STUFF(... FOR XML PATH ...) por STRING_AGG o una alternativa equivalente.",
        alcance="procedimiento",
        activo=True,
    ),
    "FN_SPLIT_PROHIBIDO": ReglaDiccionario(
        codigo="FN_SPLIT_PROHIBIDO",
        nombre="FN_SPLIT prohibido",
        severidad="alto",
        descripcion="La función dbo.FN_SPLIT debe reemplazarse por STRING_SPLIT.",
        alcance="procedimiento",
        activo=True,
    ),
    "LTRIM_RTRIM_PROHIBIDO": ReglaDiccionario(
        codigo="LTRIM_RTRIM_PROHIBIDO",
        nombre="LTRIM(RTRIM(...)) prohibido",
        severidad="medio",
        descripcion="Se debe usar TRIM(...) en lugar de anidar LTRIM(RTRIM(...)).",
        alcance="procedimiento",
        activo=True,
    ),
    "NOLOCK_EN_TABLA_FISICA": ReglaDiccionario(
        codigo="NOLOCK_EN_TABLA_FISICA",
        nombre="NOLOCK en tabla física",
        severidad="alto",
        descripcion="La tabla física no debe usar WITH(NOLOCK) cuando forma parte del FROM de un UPDATE o un patrón equivalente.",
        alcance="procedimiento",
        activo=True,
    ),
    "ORDER_BY_NUMERICO_PROHIBIDO": ReglaDiccionario(
        codigo="ORDER_BY_NUMERICO_PROHIBIDO",
        nombre="ORDER BY numérico prohibido",
        severidad="medio",
        descripcion="No se permite ORDER BY 1, ORDER BY 2 o posiciones numéricas; debe ordenarse por columnas explícitas.",
        alcance="procedimiento",
        activo=True,
    ),
    "CAST_EN_JOIN_PROHIBIDO": ReglaDiccionario(
        codigo="CAST_EN_JOIN_PROHIBIDO",
        nombre="CAST en JOIN prohibido",
        severidad="alto",
        descripcion="No se permite realizar CAST dentro de una condición JOIN; debe realizarse antes del JOIN.",
        alcance="procedimiento",
        activo=True,
    ),
    "CATALOGO_SISTEMA_PROHIBIDO": ReglaDiccionario(
        codigo="CATALOGO_SISTEMA_PROHIBIDO",
        nombre="Catálogo de sistema prohibido",
        severidad="alto",
        descripcion="Los procedimientos normales no deben consultar objetos del catálogo del sistema mediante sys.",
        alcance="procedimiento",
        activo=True,
    ),
    "SQL_DINAMICO_PROHIBIDO": ReglaDiccionario(
        codigo="SQL_DINAMICO_PROHIBIDO",
        nombre="SQL dinámico prohibido",
        severidad="alto",
        descripcion="No se permite ejecutar SQL dinámico ni consultas dinámicas en procedimientos normales.",
        alcance="procedimiento",
        activo=True,
    ),
    "VARCHAR_MAX_PROHIBIDO": ReglaDiccionario(
        codigo="VARCHAR_MAX_PROHIBIDO",
        nombre="VARCHAR(MAX) prohibido",
        severidad="alto",
        descripcion="No se permite usar VARCHAR(MAX); debe definirse una longitud explícita y justificada.",
        alcance="procedimiento",
        activo=True,
    ),
    "VARBINARY_DOCUMENTO_IDENTIFICADO": ReglaDiccionario(
        codigo="VARBINARY_DOCUMENTO_IDENTIFICADO",
        nombre="VARBINARY para documento identificado",
        severidad="bajo",
        descripcion="Se identificó VARBINARY, tipo adecuado para almacenar contenido binario de archivos o documentos.",
        alcance="procedimiento",
        activo=True,
    ),
}
