# -*- coding: utf-8 -*-
"""Reglas para procedimientos almacenados normales."""

from app.reglas.reglas_base import ReglaDiccionario

REGLAS_PROCEDIMIENTOS_NORMALES = {
    "PROCEDIMIENTO_SIN_ESQUEMA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_SIN_ESQUEMA",
        nombre="Procedimiento sin esquema",
        severidad="alto",
        descripcion="El procedimiento debe indicar su esquema (CREATE y ALTER).",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_SIN_PREFIJO_PA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_SIN_PREFIJO_PA",
        nombre="Nombre sin prefijo PA_",
        severidad="alto",
        descripcion="Al crearlo, el nombre sigue el formato Esquema.PA_Tabla_Acción_Finalidad.",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_NOMBRE_INCOMPLETO": ReglaDiccionario(
        codigo="PROCEDIMIENTO_NOMBRE_INCOMPLETO",
        nombre="Nombre de procedimiento incompleto",
        severidad="alto",
        descripcion="Al crearlo, el nombre indica la tabla y la acción: PA_Tabla_Acción_Finalidad.",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_ACCION_NO_ABREVIADA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_ACCION_NO_ABREVIADA",
        nombre="Acción sin abreviar",
        severidad="alto",
        descripcion="Las acciones estándar se abrevian: Sel (consultar), Upd (actualizar), Ins (insertar) y Del (eliminar).",
        alcance="procedimiento",
        activo=True,
    ),
    "HINT_PLAN_PROHIBIDO": ReglaDiccionario(
        codigo="HINT_PLAN_PROHIBIDO",
        nombre="Comando que le dice al motor qué hacer",
        severidad="alto",
        descripcion="No se permiten instrucciones que fuerzan al motor (RECOMPILE, FORCESEEK, OPTION...).",
        alcance="procedimiento",
        activo=True,
    ),
    "NOLOCK_EN_TABLA_TEMPORAL": ReglaDiccionario(
        codigo="NOLOCK_EN_TABLA_TEMPORAL",
        nombre="NOLOCK en tabla temporal",
        severidad="alto",
        descripcion="Las tablas temporales no deben usar WITH(NOLOCK).",
        alcance="procedimiento",
        activo=True,
    ),
    "TEMPORAL_TEXTO_SIN_COLLATE": ReglaDiccionario(
        codigo="TEMPORAL_TEXTO_SIN_COLLATE",
        nombre="Columna de texto sin COLLATE en tabla temporal",
        severidad="alto",
        descripcion="Las columnas de texto de tablas temporales deben declarar COLLATE.",
        alcance="procedimiento",
        activo=True,
    ),
    "SELECT_INTO_PROHIBIDO": ReglaDiccionario(
        codigo="SELECT_INTO_PROHIBIDO",
        nombre="SELECT INTO prohibido",
        severidad="alto",
        descripcion="Se crea la tabla temporal con CREATE TABLE y se llena con INSERT INTO.",
        alcance="procedimiento",
        activo=True,
    ),
    "SELECT_ESTRELLA_PROHIBIDO": ReglaDiccionario(
        codigo="SELECT_ESTRELLA_PROHIBIDO",
        nombre="SELECT estrella prohibido",
        severidad="medio",
        descripcion="Las consultas deben indicar sus columnas explícitamente.",
        alcance="procedimiento",
        activo=True,
    ),
    "CODIGO_SQL_COMENTADO": ReglaDiccionario(
        codigo="CODIGO_SQL_COMENTADO",
        nombre="Código SQL comentado",
        severidad="medio",
        descripcion="El procedimiento no debe conservar sentencias SQL comentadas que no aporten.",
        alcance="procedimiento",
        activo=True,
    ),
    "VARIABLE_DECLARADA_SIN_USO": ReglaDiccionario(
        codigo="VARIABLE_DECLARADA_SIN_USO",
        nombre="Variable declarada sin uso",
        severidad="medio",
        descripcion="Toda variable declarada debe utilizarse en el procedimiento.",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_SIN_ACCION": ReglaDiccionario(
        codigo="PROCEDIMIENTO_SIN_ACCION",
        nombre="Nombre sin acción",
        severidad="alto",
        descripcion="Después de la tabla va la acción: Sel, Upd, Ins, Del o un verbo personalizado.",
        alcance="procedimiento",
        activo=True,
    ),
    "PROCEDIMIENTO_NOMBRE_NO_PASCALCASE": ReglaDiccionario(
        codigo="PROCEDIMIENTO_NOMBRE_NO_PASCALCASE",
        nombre="Nombre de procedimiento fuera del estándar",
        severidad="alto",
        descripcion="Tabla, acción y finalidad van en PascalCase (ej.: PA_Cliente_Sel_PorDocumento).",
        alcance="procedimiento",
        activo=True,
    ),
    "WAITFOR_DELAY_PROHIBIDO": ReglaDiccionario(
        codigo="WAITFOR_DELAY_PROHIBIDO",
        nombre="WAITFOR prohibido",
        severidad="alto",
        descripcion="No se permite pausar la ejecución con WAITFOR DELAY o WAITFOR TIME.",
        alcance="procedimiento",
        activo=True,
    ),
    "ESQUEMA_OMITIDO_ENTRE_BASES": ReglaDiccionario(
        codigo="ESQUEMA_OMITIDO_ENTRE_BASES",
        nombre="Esquema omitido entre bases",
        severidad="alto",
        descripcion="Al consultar otra base de datos se escribe Base.Esquema.Tabla, no Base..Tabla.",
        alcance="procedimiento",
        activo=True,
    ),
    "TABLA_REPETIDA_EN_CONSULTA": ReglaDiccionario(
        codigo="TABLA_REPETIDA_EN_CONSULTA",
        nombre="Misma tabla en varios JOIN",
        severidad="medio",
        descripcion="Una misma tabla no debe leerse más de 3 veces (FROM/JOIN) en la misma consulta.",
        alcance="procedimiento",
        activo=True,
    ),
    "RAISERROR_USAR_THROW": ReglaDiccionario(
        codigo="RAISERROR_USAR_THROW",
        nombre="Usar THROW en lugar de RAISERROR",
        severidad="medio",
        descripcion="Para lanzar errores se recomienda THROW en lugar de RAISERROR.",
        alcance="procedimiento",
        activo=True,
    ),
    "IN_CON_UN_SOLO_VALOR": ReglaDiccionario(
        codigo="IN_CON_UN_SOLO_VALOR",
        nombre="IN con un solo valor",
        severidad="medio",
        descripcion="IN se usa con dos o más valores; con uno solo se usa = (o <> en lugar de NOT IN).",
        alcance="procedimiento",
        activo=True,
    ),
    "LEFT_REEMPLAZABLE_POR_LIKE": ReglaDiccionario(
        codigo="LEFT_REEMPLAZABLE_POR_LIKE",
        nombre="LEFT que puede ser LIKE",
        severidad="medio",
        descripcion="En una condición, LEFT(col, n) = 'abc' se reemplaza por col LIKE 'abc%' para usar los índices.",
        alcance="procedimiento",
        activo=True,
    ),
    "REPLACE_ANIDADO_TRANSLATE": ReglaDiccionario(
        codigo="REPLACE_ANIDADO_TRANSLATE",
        nombre="REPLACE anidados que pueden ser TRANSLATE",
        severidad="medio",
        descripcion="Tres o más REPLACE anidados que cambian caracteres sueltos se reemplazan por TRANSLATE.",
        alcance="procedimiento",
        activo=True,
    ),
    "TRANSACCION_SIN_COMMIT": ReglaDiccionario(
        codigo="TRANSACCION_SIN_COMMIT",
        nombre="Transacción sin COMMIT",
        severidad="alto",
        descripcion="Toda transacción abierta con BEGIN TRANSACTION debe confirmarse con COMMIT.",
        alcance="procedimiento",
        activo=True,
    ),
    "WHILE_PROHIBIDO": ReglaDiccionario(
        codigo="WHILE_PROHIBIDO",
        nombre="WHILE prohibido",
        severidad="alto",
        descripcion="No se permite el uso de bucles WHILE en procedimientos normales; use operaciones basadas en conjuntos.",
        alcance="procedimiento",
        activo=True,
    ),
    "GOTO_PROHIBIDO": ReglaDiccionario(
        codigo="GOTO_PROHIBIDO",
        nombre="Uso de GOTO",
        severidad="medio",
        descripcion="No se permite el uso de GOTO en procedimientos normales.",
        alcance="procedimiento",
        activo=True,
    ),
    "MERGE_PROHIBIDO": ReglaDiccionario(
        codigo="MERGE_PROHIBIDO",
        nombre="Uso de MERGE",
        severidad="medio",
        descripcion="No se permite la sentencia MERGE en procedimientos normales.",
        alcance="procedimiento",
        activo=True,
    ),
    "COLLATE_EN_PREDICADO": ReglaDiccionario(
        codigo="COLLATE_EN_PREDICADO",
        nombre="COLLATE en predicado",
        severidad="alto",
        descripcion="No debe usarse COLLATE dentro de condiciones WHERE o JOIN; debe definirse en la tabla temporal o columna.",
        alcance="procedimiento",
        activo=True,
    ),
    "STUFF_FOR_XML_PATH_PROHIBIDO": ReglaDiccionario(
        codigo="STUFF_FOR_XML_PATH_PROHIBIDO",
        nombre="STUFF con FOR XML PATH prohibido",
        severidad="alto",
        descripcion="Se debe reemplazar STUFF(... FOR XML PATH ...) por STRING_AGG o una alternativa equivalente.",
        alcance="procedimiento",
        activo=True,
    ),
    "FN_SPLIT_PROHIBIDO": ReglaDiccionario(
        codigo="FN_SPLIT_PROHIBIDO",
        nombre="FN_SPLIT prohibido",
        severidad="alto",
        descripcion="La función dbo.FN_SPLIT debe reemplazarse por STRING_SPLIT.",
        alcance="procedimiento",
        activo=True,
    ),
    "LTRIM_RTRIM_PROHIBIDO": ReglaDiccionario(
        codigo="LTRIM_RTRIM_PROHIBIDO",
        nombre="LTRIM(RTRIM(...)) prohibido",
        severidad="medio",
        descripcion="Se debe usar TRIM(...) en lugar de anidar LTRIM(RTRIM(...)).",
        alcance="procedimiento",
        activo=True,
    ),
    "NOLOCK_EN_TABLA_FISICA": ReglaDiccionario(
        codigo="NOLOCK_EN_TABLA_FISICA",
        nombre="NOLOCK en tabla física",
        severidad="alto",
        descripcion="La tabla física no debe usar WITH(NOLOCK) cuando forma parte del FROM de un UPDATE o un patrón equivalente.",
        alcance="procedimiento",
        activo=True,
    ),
    "ORDER_BY_NUMERICO_PROHIBIDO": ReglaDiccionario(
        codigo="ORDER_BY_NUMERICO_PROHIBIDO",
        nombre="ORDER BY numérico prohibido",
        severidad="medio",
        descripcion="No se permite ORDER BY 1, ORDER BY 2 o posiciones numéricas; debe ordenarse por columnas explícitas.",
        alcance="procedimiento",
        activo=True,
    ),
    "CAST_EN_JOIN_PROHIBIDO": ReglaDiccionario(
        codigo="CAST_EN_JOIN_PROHIBIDO",
        nombre="CAST o CONVERT en JOIN",
        severidad="alto",
        descripcion="No se permite realizar CAST dentro de una condición JOIN; debe realizarse antes del JOIN.",
        alcance="procedimiento",
        activo=True,
    ),
    "CATALOGO_SISTEMA_PROHIBIDO": ReglaDiccionario(
        codigo="CATALOGO_SISTEMA_PROHIBIDO",
        nombre="Catálogo de sistema prohibido",
        severidad="alto",
        descripcion="Los procedimientos normales no deben consultar objetos del catálogo del sistema mediante sys.",
        alcance="procedimiento",
        activo=True,
    ),
    "SQL_DINAMICO_PROHIBIDO": ReglaDiccionario(
        codigo="SQL_DINAMICO_PROHIBIDO",
        nombre="SQL dinámico prohibido",
        severidad="alto",
        descripcion="No se permite ejecutar SQL dinámico ni consultas dinámicas en procedimientos normales.",
        alcance="procedimiento",
        activo=True,
    ),
    "VARCHAR_MAX_PROHIBIDO": ReglaDiccionario(
        codigo="VARCHAR_MAX_PROHIBIDO",
        nombre="VARCHAR(MAX) prohibido",
        severidad="medio",
        descripcion="No se permite usar VARCHAR(MAX); debe definirse una longitud explícita y justificada.",
        alcance="procedimiento",
        activo=True,
    ),
    "VARBINARY_DOCUMENTO_IDENTIFICADO": ReglaDiccionario(
        codigo="VARBINARY_DOCUMENTO_IDENTIFICADO",
        nombre="VARBINARY para documento identificado",
        severidad="bajo",
        descripcion="Se identificó VARBINARY, tipo adecuado para almacenar contenido binario de archivos o documentos.",
        alcance="procedimiento",
        activo=True,
    ),
}
