# -*- coding: utf-8 -*-
"""Reglas para procedimientos de reportes."""

from app.reglas.reglas_base import ReglaDiccionario

REGLAS_REPORTES = {
    "TABLA_FISICA_SIN_NOLOCK": ReglaDiccionario(
        codigo="TABLA_FISICA_SIN_NOLOCK",
        nombre="Tabla física sin NOLOCK",
        severidad="alto",
        descripcion="Las tablas físicas consultadas por un reporte deben usar WITH(NOLOCK).",
        alcance="reporte",
        activo=True,
    ),
    "NOLOCK_EN_TABLA_TEMPORAL": ReglaDiccionario(
        codigo="NOLOCK_EN_TABLA_TEMPORAL",
        nombre="NOLOCK en tabla temporal",
        severidad="alto",
        descripcion="Las tablas temporales no deben utilizar WITH(NOLOCK).",
        alcance="reporte",
        activo=True,
    ),
    "HINT_PLAN_PROHIBIDO": ReglaDiccionario(
        codigo="HINT_PLAN_PROHIBIDO",
        nombre="Comando que le dice al motor qué hacer",
        severidad="alto",
        descripcion="No se permiten comandos que le dicen al motor qué hacer (DBCC, FORCESEEK, RECOMPILE, OPTION...); el optimizador decide el mejor plan.",
        alcance="reporte",
        activo=True,
    ),
    "CODIGO_SQL_COMENTADO": ReglaDiccionario(
        codigo="CODIGO_SQL_COMENTADO",
        nombre="Código SQL comentado",
        severidad="medio",
        descripcion="El reporte no debe conservar sentencias SQL comentadas que no aporten.",
        alcance="reporte",
        activo=True,
    ),
    "TEMPORAL_TEXTO_SIN_COLLATE": ReglaDiccionario(
        codigo="TEMPORAL_TEXTO_SIN_COLLATE",
        nombre="Texto temporal sin COLLATE",
        severidad="alto",
        descripcion="Las columnas de texto de tablas temporales deben declarar COLLATE.",
        alcance="reporte",
        activo=True,
    ),
    "SELECT_INTO_PROHIBIDO": ReglaDiccionario(
        codigo="SELECT_INTO_PROHIBIDO",
        nombre="SELECT INTO prohibido",
        severidad="alto",
        descripcion="Se debe declarar la tabla temporal y luego insertar sus datos.",
        alcance="reporte",
        activo=True,
    ),
    "SELECT_ESTRELLA_PROHIBIDO": ReglaDiccionario(
        codigo="SELECT_ESTRELLA_PROHIBIDO",
        nombre="SELECT estrella prohibido",
        severidad="medio",
        descripcion="Las consultas deben indicar sus columnas explícitamente.",
        alcance="reporte",
        activo=True,
    ),
    "IN_CON_UN_SOLO_VALOR": ReglaDiccionario(
        codigo="IN_CON_UN_SOLO_VALOR",
        nombre="IN con un solo valor",
        severidad="medio",
        descripcion="Use igualdad cuando IN contiene un único valor.",
        alcance="reporte",
        activo=True,
    ),
    "CATALOGO_SISTEMA_PROHIBIDO": ReglaDiccionario(
        codigo="CATALOGO_SISTEMA_PROHIBIDO",
        nombre="Catálogo de sistema prohibido",
        severidad="alto",
        descripcion="Un procedimiento de reporte no debe consultar catálogos del sistema.",
        alcance="reporte",
        activo=True,
    ),
    "MODIFICACION_TABLA_FISICA": ReglaDiccionario(
        codigo="MODIFICACION_TABLA_FISICA",
        nombre="Modificación de tabla física",
        severidad="critico",
        descripcion="Los reportes solo consultan y no modifican tablas físicas.",
        alcance="reporte",
        activo=True,
    ),
    "VARIABLE_DECLARADA_SIN_USO": ReglaDiccionario(
        codigo="VARIABLE_DECLARADA_SIN_USO",
        nombre="Variable declarada sin uso",
        severidad="medio",
        descripcion="Toda variable declarada debe utilizarse en la lógica del reporte.",
        alcance="reporte",
        activo=True,
    ),
    "SQL_DINAMICO_PROHIBIDO": ReglaDiccionario(
        codigo="SQL_DINAMICO_PROHIBIDO",
        nombre="SQL dinámico prohibido",
        severidad="alto",
        descripcion="No se permite ejecutar SQL dinámico ni consultas dinámicas en reportes.",
        alcance="reporte",
        activo=True,
    ),
    "VARCHAR_MAX_PROHIBIDO": ReglaDiccionario(
        codigo="VARCHAR_MAX_PROHIBIDO",
        nombre="VARCHAR(MAX) prohibido",
        severidad="alto",
        descripcion="VARCHAR(MAX) solo se permite para guardar JSON o XML; en otro caso se define una longitud.",
        alcance="reporte",
        activo=True,
    ),
    "WHILE_PROHIBIDO": ReglaDiccionario(
        codigo="WHILE_PROHIBIDO",
        nombre="WHILE prohibido",
        severidad="alto",
        descripcion="Un procedimiento de reporte nuevo (CREATE) no debe usar WHILE; en un ALTER no se observa.",
        alcance="reporte",
        activo=True,
    ),
    "RAISERROR_USAR_THROW": ReglaDiccionario(
        codigo="RAISERROR_USAR_THROW",
        nombre="Usar THROW en lugar de RAISERROR",
        severidad="medio",
        descripcion="Para lanzar errores se recomienda THROW en lugar de RAISERROR.",
        alcance="reporte",
        activo=True,
    ),
    "WAITFOR_DELAY_PROHIBIDO": ReglaDiccionario(
        codigo="WAITFOR_DELAY_PROHIBIDO",
        nombre="WAITFOR prohibido",
        severidad="alto",
        descripcion="Un reporte no debe pausar su ejecución con WAITFOR DELAY o WAITFOR TIME.",
        alcance="reporte",
        activo=True,
    ),
    "PROCEDIMIENTO_SIN_ESQUEMA": ReglaDiccionario(
        codigo="PROCEDIMIENTO_SIN_ESQUEMA",
        nombre="Procedimiento sin esquema",
        severidad="alto",
        descripcion="El procedimiento del reporte indica su esquema (dbo.), tanto en CREATE como en ALTER.",
        alcance="reporte",
        activo=True,
    ),
    "ESQUEMA_OMITIDO_ENTRE_BASES": ReglaDiccionario(
        codigo="ESQUEMA_OMITIDO_ENTRE_BASES",
        nombre="Esquema omitido entre bases",
        severidad="alto",
        descripcion="Al consultar otra base de datos se escribe Base.Esquema.Tabla, no Base..Tabla.",
        alcance="reporte",
        activo=True,
    ),
    "ORDER_BY_NUMERICO_PROHIBIDO": ReglaDiccionario(
        codigo="ORDER_BY_NUMERICO_PROHIBIDO",
        nombre="ORDER BY numérico prohibido",
        severidad="medio",
        descripcion="No se ordena por posición (ORDER BY 1, 2); se escribe el nombre de la columna.",
        alcance="reporte",
        activo=True,
    ),
    "COLLATE_EN_PREDICADO": ReglaDiccionario(
        codigo="COLLATE_EN_PREDICADO",
        nombre="COLLATE en WHERE o JOIN",
        severidad="alto",
        descripcion="No se permite COLLATE en las condiciones del WHERE ni del JOIN; se define al crear la tabla.",
        alcance="reporte",
        activo=True,
    ),
    "LTRIM_RTRIM_PROHIBIDO": ReglaDiccionario(
        codigo="LTRIM_RTRIM_PROHIBIDO",
        nombre="LTRIM y RTRIM en lugar de TRIM",
        severidad="medio",
        descripcion="Reemplazar LTRIM(RTRIM(x)) por la función nativa TRIM(x).",
        alcance="reporte",
        activo=True,
    ),
    "STUFF_FOR_XML_PATH_PROHIBIDO": ReglaDiccionario(
        codigo="STUFF_FOR_XML_PATH_PROHIBIDO",
        nombre="FOR XML PATH en lugar de STRING_AGG",
        severidad="medio",
        descripcion="Para concatenar valores se usa STRING_AGG en lugar de FOR XML PATH('') y STUFF.",
        alcance="reporte",
        activo=True,
    ),
    "FN_SPLIT_PROHIBIDO": ReglaDiccionario(
        codigo="FN_SPLIT_PROHIBIDO",
        nombre="fn_split en lugar de STRING_SPLIT",
        severidad="medio",
        descripcion="Para dividir textos se usa la función nativa STRING_SPLIT en lugar de dbo.fn_split().",
        alcance="reporte",
        activo=True,
    ),
    "VARBINARY_DOCUMENTO_IDENTIFICADO": ReglaDiccionario(
        codigo="VARBINARY_DOCUMENTO_IDENTIFICADO",
        nombre="VARBINARY para documento identificado",
        severidad="bajo",
        descripcion="Se identificó VARBINARY, tipo adecuado para almacenar contenido binario de archivos o documentos.",
        alcance="reporte",
        activo=True,
    ),
}
